// Automatically generated by build/codegen/typescript.rs. DO NOT EDIT.

declare namespace time_backend {
  @external("time_backend", "set_interval")
  function set_interval(id: u32, period_ms: u32): void;
  @external("time_backend", "delete_interval")
  function delete_interval(id: u32): void;
  @external("time_backend", "set_timeout")
  function set_timeout(id: u32, delay_ms: u32): void;
  @external("time_backend", "delete_timeout")
  function delete_timeout(id: u32): void;
}

export class Time {
  set_interval(id: u32, period_ms: u32): Set_intervalBuilder {
    return new Set_intervalBuilder(this, id, period_ms);
  }
  delete_interval(id: u32): Delete_intervalBuilder {
    return new Delete_intervalBuilder(this, id);
  }
  set_timeout(id: u32, delay_ms: u32): Set_timeoutBuilder {
    return new Set_timeoutBuilder(this, id, delay_ms);
  }
  delete_timeout(id: u32): Delete_timeoutBuilder {
    return new Delete_timeoutBuilder(this, id);
  }
}

export class Set_intervalBuilder {
  private _id: u32;
  private _period_ms: u32;
  private time: Time;
  constructor(time: Time, id: u32, period_ms: u32) {
    this.time = time;
    this._id = id;
    this._period_ms = period_ms;
  }
  draw(): void {
    time_backend.set_interval(this._id, this._period_ms);
  }
}

export class Delete_intervalBuilder {
  private _id: u32;
  private time: Time;
  constructor(time: Time, id: u32) {
    this.time = time;
    this._id = id;
  }
  draw(): void {
    time_backend.delete_interval(this._id);
  }
}

export class Set_timeoutBuilder {
  private _id: u32;
  private _delay_ms: u32;
  private time: Time;
  constructor(time: Time, id: u32, delay_ms: u32) {
    this.time = time;
    this._id = id;
    this._delay_ms = delay_ms;
  }
  draw(): void {
    time_backend.set_timeout(this._id, this._delay_ms);
  }
}

export class Delete_timeoutBuilder {
  private _id: u32;
  private time: Time;
  constructor(time: Time, id: u32) {
    this.time = time;
    this._id = id;
  }
  draw(): void {
    time_backend.delete_timeout(this._id);
  }
}

