// Automatically generated by build/codegen/typescript.rs. DO NOT EDIT.
import { Color, Point, Size, Rect, Duration } from "./types";

declare namespace timer {
  @external("timer", "create_timeout")
  function create_timeout(id: u32, duration: u64): void;
  @external("timer", "delete_timeout")
  function delete_timeout(id: u32, duration: u64): void;
}

export class Timer {
  setTimeout(id: u32, duration: Duration): SetTimeoutBuilder {
    return new SetTimeoutBuilder(this, id, duration);
  }
  clearTimeout(id: u32, duration: Duration): ClearTimeoutBuilder {
    return new ClearTimeoutBuilder(this, id, duration);
  }
}

export class SetTimeoutBuilder {
  private _id: u32;
  private _duration: Duration;
  private timer: Timer;
  constructor(timer: Timer, id: u32, duration: Duration) {
    this.timer = timer;
    this._id = id;
    this._duration = duration;
  }
  execute(): void {
    timer.create_timeout(this._id, this._duration.ticks);
  }
}

export class ClearTimeoutBuilder {
  private _id: u32;
  private _duration: Duration;
  private timer: Timer;
  constructor(timer: Timer, id: u32, duration: Duration) {
    this.timer = timer;
    this._id = id;
    this._duration = duration;
  }
  execute(): void {
    timer.delete_timeout(this._id, this._duration.ticks);
  }
}

