// Automatically generated by build/codegen/typescript.rs. DO NOT EDIT.

export class Color {
r: u8; g: u8; b: u8;
constructor(r: u8, g: u8, b: u8) { this.r = r; this.g = g; this.b = b; }
static readonly WHITE: Color = new Color(255, 255, 255);
static readonly BLACK: Color = new Color(0, 0, 0);
}

export class Point {
x: u32; y: u32;
constructor(x: u32, y: u32) { this.x = x; this.y = y; }
}

export class Size {
width: u32; height: u32;
constructor(width: u32, height: u32) { this.width = width; this.height = height; }
}

export class Rect {
x: u32; y: u32; width: u32; height: u32;
constructor(x: u32, y: u32, width: u32, height: u32) { this.x = x; this.y = y; this.width = width; this.height = height; }
}

export class Duration {
ticks: u64;
constructor(ticks: u64) { this.ticks = ticks; }
static fromMs(ms: u64): Duration { return new Duration(ms * 1000); }
static fromSec(s: u64): Duration { return new Duration(s * 1_000_000); }
static fromMin(m: u64): Duration { return new Duration(m * 60_000_000); }
}
