// Handcrafted — NOT generated by codegen. DO NOT OVERWRITE.
//
// The host writes the UTF-8 value bytes into a caller-supplied buffer and
// returns the number of bytes written, or -1 if the key is not found.

declare namespace config {
  @external("config", "get")
  function get(key_len: u32, key_ptr: usize, out_max: u32, out_ptr: usize): i32;
}

const _CONFIG_BUF_SIZE: i32 = 512;

export class Config {
  /** Returns the value for `key`, or `null` if it is not set. */
  get(key: string): string | null {
    const keyBuf = String.UTF8.encode(key);
    const outBuf = new ArrayBuffer(_CONFIG_BUF_SIZE);
    const len = config.get(
      keyBuf.byteLength,
      changetype<usize>(keyBuf),
      outBuf.byteLength,
      changetype<usize>(outBuf),
    );
    if (len < 0) return null;
    return String.UTF8.decodeUnsafe(changetype<usize>(outBuf), len);
  }

  /** Returns the value for `key`, or `fallback` if it is not set. */
  getOr(key: string, fallback: string): string {
    const v = this.get(key);
    return v !== null ? (v as string) : fallback;
  }
}
